#!/bin/bash

echo "Content-Type: text/html"
echo "Content:"
echo

mkdir .CGISwiftCompile

# Copy libraries
cp /usr/local/lib/SwiftyWeb.swift .CGISwiftCompile/SwiftyWeb.swift
cp /usr/local/lib/SwiftyHTM.swift .CGISwiftCompile/SwiftyHTM.swift

# Setup Swift files
cp ${@:$#} .CGISwiftCompile/main.swift &> /dev/null
cp ${@:1:$(($#-1))} .CGISwiftCompile/ &> /dev/null

# Compile
swiftc .CGISwiftCompile/* 2>&1

# Run
./main

# Remove all
rm -rf .CGISwiftCompile
rm main

